import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Nav'
import TopLeftImg from './components/TopLeftImg'


// fonts
import { Sora } from "next/font/google"; '@next/font/google';

//  font assing
const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
});


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"page bg-site text-white bg-cover bg-no-repeat ${sora.vaiable} font-sora relative "}>


        <TopLeftImg />
        <Navbar />


        {children}
      </body>
    </html>
  )
}
